= Backup strategy

== Overview

=== Client
> Client snapshots are saved to a drive formatted with XFS.  This is because it is faster for this usecase than Btrfs and is less likely to experience inode exhaustion using it's default config than other file systems.

A backup script using rsync to make snapshots every 2 hours to a remote host storing the snapshots by datestamp directory in a directory named the same as the client host.  This script is installed via salt-minion.  A list of excludes is read from ~/.config/backup/excludes.txt and mostly contains caches, ISO files, and flatpack blobs.

=== Server
> The backup destination drive mounted at /srv/backup is formatted with Btrfs

1. Scan /srv/snapshots to get all client hostname folders
3. Run, in parallel
	1. Generate a hash file for each client hostname folder's contents using find | xargs b3sum >> /srv/backup/<client_hostname>_<datestamp>.b3sum
	2. lrztar | blkar each folder to /srv/backup/<client_hostname>_<datestamp>.lrz.blkar
4. Rsync the tools used to the /srv/backup/tools folder
5. Run pruning script
6. Run filesystem defragmentation
7. Run bees
8. Run borgmatic to borg backup the backup drive at /srv/backup to borgbase

== Borg Backup
Borg is used to keep offsite backup sizes small.  It is not meant for convenience.  Because of how I've structured the backup folder and it's contents, it would be trivial to extract the b3sum files and parse them to find the host and file/directory I'm looking for so I can get the correct path for a borg export-tar command in the event my local sources are not available.  In the latter case, it is also assumed I'll probably need everything anyway.
